version: '3.1'

services:
  
  mysql-server:
    image: mysql:latest
    container_name: local-mysql-server
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: local-phpmyadmin-app
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80