version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    command: ["-f", "/etc/mongod.conf"]
    volumes:
      - ./config/mongod.conf:/etc/mongod.conf
      - ./data/db:/data/db
      - ./log/:/var/log/mongodb/

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: midnight
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: rootpassword
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: "mongodb://root:rootpassword@mongo:27017"
    ports:
      - 8087:8081