version: '3.1'

services:
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: local-rabbitmq-server
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data/:/var/lib/rabbitmq/
        - ./log/:/var/log/rabbitmq